GET http://localhost:5000/users

###

POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "Dinesh",
    "password": "password"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "name": "Dinesh1",
    "password": "passwod"
}